#!/usr/bin/env bash

git submodule update --init --recursive

for f in *; do

  file=$(basename "$f")

  if [[ "$file" != .*  && "$file" != "install" ]]; then
    cp -r -T $file ~/.$file;
  fi

done

vim +PluginInstall +qall
